### ISSUE TITLE
HTML-Minifier-Terser-Sync?

### ISSUE THREAD

**Issue by TheJaredWilcurt** [overlookmotel/terser-sync#7]
Could you also make a sync version of `html-minifier-terser`?

* https://www.npmjs.com/package/html-minifier-terser

Just for me? Your one and only GitHub Star :star:!

**Comment by overlookmotel** [comment]
Hahaha! Funny, but no. I only made this package because I needed it. And like any good DJ, I don't take requests.

In any case this package is a bit of a disgrace! It monkey-patches Terser to achieve it's goal, but will probably break at some point in the future.

If that doesn't bother you, you could likely cook up a similar solution for the HTML minifier using this repo as a guide.

Sorry to disappoint you, avid fan.

**Comment by TheJaredWilcurt** [comment]
My hopes and dreams have been crushed by reality.

Now I will be forced to prioritize making my synchronous library asynchronous. FORSOOTH!
